export enum DomainErrorCode {
  // Barber
  BARBER_NOT_FOUND = 'BARBER_NOT_FOUND',
  BARBER_HAS_BOOKINGS = 'BARBER_HAS_BOOKINGS',

  // Establishment
  ESTABLISHMENT_NOT_FOUND = 'ESTABLISHMENT_NOT_FOUND',
  ESTABLISHMENT_HAS_BOOKINGS = 'ESTABLISHMENT_HAS_BOOKINGS',

  // Booking / Appointment
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_EXPIRED = 'BOOKING_EXPIRED',
  BOOKING_CONFLICT = 'BOOKING_CONFLICT',
  BOOKING_INVALID_TRANSITION = 'BOOKING_INVALID_TRANSITION',
  BOOKING_ALREADY_CONFIRMED = 'BOOKING_ALREADY_CONFIRMED',

  // Client
  CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND',

  // Service
  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  BARBER_DOES_NOT_OFFER_SERVICE = 'BARBER_DOES_NOT_OFFER_SERVICE',

  // Validation
  INVALID_PHONE = 'INVALID_PHONE',
  INVALID_NAME = 'INVALID_NAME',
  DATE_TOO_FAR = 'DATE_TOO_FAR',

  // Auth / Rate Limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Payment
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_INVALID_TRANSITION = 'PAYMENT_INVALID_TRANSITION',

  // Generic
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  ENTITY_DELETED = 'ENTITY_DELETED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
